### ISSUE TITLE
[DEFECT] Taxable <tag> on Repeating CashFlows doesn't change

### ISSUE THREAD

**Issue by klfrick2** [idaholab/HERON#126]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
When inputting 

`<CashFlow name="h2_credit" type="repeating" taxable='False' inflation='none' mult_target='False'>
          <driver>
			<activity>hydrogen</activity>
			<multiplier>1.0</multiplier>
          </driver>
          <reference_price>
			<fixed_value>3.0</fixed_value>
          </reference_price>
        </CashFlow>`

I expected the system to not tax this cash flow since the Taxable='False' tag is applied. 

##### What did you see instead?
Tax was taken out of the h2_credit sales. 

##### Do you have a suggested fix for the development team?
Perhaps the mask just isn't working the same way it would for a non-taxable capex. So modifying to match this would make sense. 

**Describe how to Reproduce**
1. Make a non-taxable repeating cash flow. 
2. Add in tax to the HERON run (25% maybe)
3. run the case and look at the out~inner file to see the difference between the normal cash flow and the Time Adjusted Cashflow. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
As it turns out, in the DispatchManager when we transfer from HERON CashFlows to TEAL CashFlows (after optimization), we are passing the "name" and "Life_time" but not the tax or inflation. See lines 338 and 347.

This is not correct; sometimes a user wants to change behavior and HERON should let them do that.

**Comment by dylanjm** [comment]
Closing as it is a repeat of #265
