### ISSUE TITLE
[DEFECT] The "debug" mode is not a valid mode of operation

### ISSUE THREAD

**Issue by BotrosHanna-INL** [idaholab/HERON#133]
--------
Defect Description
--------

The "debug" mode is not a mode of operation for any case in the test cases in the folder: raven/plugins/HERON/tests

##### What did you expect to see happen?
Expected the capability to switch the mode of operation to "debug" as described in the docs.

##### What did you see instead?
An error message (see the image)
<img width="975" alt="image" src="https://user-images.githubusercontent.com/99109297/153816020-30004942-341f-4cf7-9341-c40408aa950f.png">

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. Change the "mode" to "debug" mode in the "heron_input.xml" file into one of t he test cases in the folder: raven/plugins/HERON/tests 
2. Run Heron: projects/raven/plugins/HERON/heron heron_input.xml 

**Screenshots and Input Files**
[heron_input1.txt](https://github.com/idaholab/HERON/files/8058719/heron_input1.txt)

**Platform (please complete the following information):**
 - macOS Monterey 12.2 
 
 - Dependencies Installation: Conda3

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved to close via #136.
