### ISSUE TITLE
[DEFECT] Building documentation broken for Windows

### ISSUE THREAD

**Issue by dgarrett622** [idaholab/HERON#134]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
There seem to be two methods to build the documentation on Windows. At least one of these methods should work.

##### What did you see instead?
Method 1:
Using git bash, running `bash make_docs.sh` under /HERON/doc/ gives the following error:
```
Building manuals ...
... building in user_manual...
bash: make_win.sh: No such file or directory
... ... failed to make docs in user_manual
```

Method 2:
Using git bash, running `bash make_docs.bat` under /HERON/doc/user_manual/ gives the following error:
```
Starting to compile manual...
make_docs.bat: line 4: copy_tex.sh: command not found
```

##### Do you have a suggested fix for the development team?
For method 1, there needs to be a `make_win.sh` file.
For method 2, changing line 4 of `make_docs.bat` to `bash copy_tex.sh` should fix this issue.

**Describe how to Reproduce**
1. Run `bash make_docs.sh` under /HERON/doc/ with git bash on Windows
2. Run `bash make_docs.bat` under /HERON/doc/user_manual/ with git bash on Windows
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Dependencies Installation: CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dgarrett622** [comment]
As an update, changing line 4 of make_docs.bat to `./copy_tex.sh` runs the script as well as `bash copy_tex.sh`. I think `bash copy_tex.sh` would be more general.

**Comment by PaulTalbot-INL** [comment]
Especially for the `.bat` file, which is just for Windows, I think that's a good suggestion.

**Comment by PaulTalbot-INL** [comment]
@worseliz any thoughts on this issue? What was working for you?

**Comment by PaulTalbot-INL** [comment]
Approved to close via #135.
