### ISSUE TITLE
[DEFECT] Bug in Debug Mode with Optimization Settings

### ISSUE THREAD

**Issue by dylanjm** [idaholab/HERON#158]
--------
Defect Description
--------

There is currently a bug in `template_driver.py` inside the `_modify_outer_dataobjects()` method. If `<debug/>` is specified in an input file, and `<mode>opt</mode>`, and then `<optimization_settings>` are set. Then the HERON template writer will error out. 

The offending code has to do with this logic:

```python3
    DOs = template.find('DataObjects')
    # labels pass to inner
    if case.get_labels():
      for node in DOs:
        if node.get('name') == 'grid':
          input_node = node.find('Input')
          input_node.text += ', GRO_case_labels'
    # remove opt components if not used
    if case.get_mode() == 'sweep' or case.debug['enabled']:
      self._remove_by_name(DOs, ['opt_eval', 'opt_soln'])
    elif case.get_mode() == 'opt':
      self._remove_by_name(DOs, ['grid'])
    # update optimization settings if provided
    if (case.get_mode() == 'opt') and (case._optimization_settings is not None):
      new_opt_objective = self._build_opt_metric_out_name(case)
      # check if the metric in 'opt_eval' needs to be changed
      opt_eval_output_node = DOs.find(".//PointSet[@name='opt_eval']").find('Output')
```

Where it will fail on the last line with the error:

```
Traceback (most recent call last):
  File "/Users/mcdodj/Documents/projects/HERON/src/main.py", line 100, in <module>
    sim.create_raven_workflow()
  File "/Users/mcdodj/Documents/projects/HERON/src/main.py", line 90, in create_raven_workflow
    case.write_workflows(self._components, self._sources, self._input_dir)
  File "/Users/mcdodj/Documents/projects/HERON/src/Cases.py", line 699, in write_workflows
    inner, outer, cash = template_class.createWorkflow(self, components, sources)
  File "/Users/mcdodj/Documents/projects/HERON/templates/template_driver.py", line 140, in createWorkflow
    outer = self._modify_outer(outer, case, components, sources)
  File "/Users/mcdodj/Documents/projects/HERON/templates/template_driver.py", line 205, in _modify_outer
    self._modify_outer_dataobjects(template, case, components)
  File "/Users/mcdodj/Documents/projects/HERON/templates/template_driver.py", line 350, in _modify_outer_dataobjects
    opt_eval_output_node = DOs.find(".//PointSet[@name='opt_eval']").find('Output')
AttributeError: 'NoneType' object has no attribute 'find'
```

##### What did you expect to see happen?

I expected that debug mode should run when I tell it to. 

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Currently solved by #161. Archiving for future reference.
