### ISSUE TITLE
ARMA for electric grid not able to access variables

### ISSUE THREAD

**Issue by andrewtrainor** [idaholab/HERON#18]
--------

I have created a model that uses a steam generator that then uses a turbine to convert the steam to electricity. The electricity is then is consumed by two power grids. The primary grid that the electricity goes to has a load that is characterised by an ARMA model. For this model there are two ARMAs the first one is used for economic stuff as used in the production_flex test, and another one describes the demand for the power grid. This code runs great when I have the primary power grid at a fixed value but as soon as I change it to use an ARMA it breaks. I have been following the instruction manual that I built from the docs folder but it doesn't offer very much information for this part.

--------

It gave this error:
```
Traceback (most recent call last):
  File "/home/prism/repos/HERON/src/main.py", line 96, in <module>
    sim.read_input(args.xml_input_file) # TODO expand to use arguments?
  File "/home/prism/repos/HERON/src/main.py", line 52, in read_input
    objects = input_loader.parse(inp, location, self.messageHandler)
  File "/home/prism/repos/HERON/src/input_loader.py", line 58, in parse
    comp.read_input(comp_xml, case.get_mode())
  File "/home/prism/repos/HERON/src/Components.py", line 121, in read_input
    demand.read_input(item, mode, self.name)
  File "/home/prism/repos/HERON/src/Components.py", line 1085, in read_input
    Interaction.read_input(self, specs, mode, comp_name)
  File "/home/prism/repos/HERON/src/Components.py", line 412, in read_input
    self._set_valued_param(name, comp_name, item, mode)
  File "/home/prism/repos/HERON/src/Components.py", line 442, in _set_valued_param
    signal = vp.read(comp, spec, mode)
  File "/home/prism/repos/HERON/src/ValuedParams.py", line 152, in read
    typ, node, signal, request = self._load(comp_name, spec, mode, alias_dict)
  File "/home/prism/repos/HERON/src/ValuedParams.py", line 238, in _load
    signals = item.findFirst('ARMA').parameterValues['variable']
KeyError: 'variable'
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[heron_input.txt](https://github.com/idaholab/HERON/files/5190242/heron_input.txt)
----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by andrewtrainor** [comment]
sorry it didn't past my code in correctly.
<HERON>
  <TestInfo>
    <name>production</name>
    <author>sexydrew</author>
    <created>2020-06-15</created>
    <description>
      I am pretty sure that this is changing the npp to meet the arma
      trained on the caiso grid. 
    </description>
    <classesTested>HERON</classesTested>
  </TestInfo>

  <Case name="Sweep_Runs">
    <num_arma_samples>10</num_arma_samples>
    <time_discretization>
      <time_variable>Time</time_variable>
      <end_time>2</end_time>
      <num_steps>31</num_steps> 
    </time_discretization>
    <economics>
      <ProjectTime>3</ProjectTime>
      <DiscountRate>0.08</DiscountRate>
      <tax>0.0</tax>
      <inflation>0.0</inflation>
      <verbosity>50</verbosity>
    </economics>
    <dispatcher>
      <type>pyomo</type>
    </dispatcher>
  </Case>

  <Components>
    <Component name="npp">
      <produces resource="steam" dispatch="independent">
        <capacity resource="steam">
          <sweep_values>26000,22000</sweep_values>
          
        </capacity>
        
      </produces>
      <economics>
        <lifetime>27</lifetime>
      </economics>
    </Component>

    <Component name="turbine">
      <produces resource="electricity" dispatch="dependent">
        <consumes>steam</consumes>
        <capacity resource="steam">
          <fixed_value>-1e10</fixed_value>
        </capacity>
        <transfer>
          <linear>
            <rate resource="steam">-1</rate>
            <rate resource="electricity">0.5</rate>
          </linear>
        </transfer>
        
      </produces>
      <economics>
        <lifetime>27</lifetime>
        
      </economics>
    </Component>

    <Component name="electr_market">
      <demands resource="electricity" dispatch="dependent">
        <capacity>
          
          <fixed_value>0</fixed_value>
        </capacity>
      </demands>
      <economics>
        <lifetime>30</lifetime>
        <CashFlow name="e_sales" type="repeating" taxable='True' inflation='none' mult_target='False'>
          <driver>
            <Function method="electric_consume">transfers</Function>
            
          </driver>
          <reference_price>
            <fixed_value>0.5</fixed_value>
          </reference_price>
        </CashFlow>
      </economics>
    </Component>

   

    <Component name="electr_flex">
      <demands resource="electricity" dispatch="independent">
        <capacity>
          <ARMA>Load</ARMA>
          
        </capacity>
      </demands>
      <economics>
        <lifetime>30</lifetime>
        <CashFlow name="e_sales" type="repeating" taxable='True' inflation='none' mult_target='False'>
          <driver>
            <Function method="electric_consume">transfers</Function>
          </driver>
          <reference_price>
            <Function method="flex_price">transfers</Function>
          </reference_price>
        </CashFlow>
      </economics>
    </Component>

  </Components>

  <DataGenerators>
    <ARMA name='Signal' variable="Signal">arma1.pk</ARMA>
    <ARMA name='Load' variable="Time">arma.pk</ARMA>
    <Function name="transfers">transfers.py</Function>
  </DataGenerators>

</HERON>

**Comment by andrewtrainor** [comment]
sorry it didn't paste my code correctly.

"""
<HERON>
  <TestInfo>
    <name>production</name>
    <author>sexydrew</author>
    <created>2020-06-15</created>
    <description>
      I am pretty sure that this is changing the npp to meet the arma
      trained on the caiso grid. 
    </description>
    <classesTested>HERON</classesTested>
  </TestInfo>

  <Case name="Sweep_Runs">
    <num_arma_samples>10</num_arma_samples>
    <time_discretization>
      <time_variable>Time</time_variable>
      <end_time>2</end_time>
      <num_steps>31</num_steps> 
    </time_discretization>
    <economics>
      <ProjectTime>3</ProjectTime>
      <DiscountRate>0.08</DiscountRate>
      <tax>0.0</tax>
      <inflation>0.0</inflation>
      <verbosity>50</verbosity>
    </economics>
    <dispatcher>
      <type>pyomo</type>
    </dispatcher>
  </Case>

  <Components>
    <Component name="npp">
      <produces resource="steam" dispatch="independent">
        <capacity resource="steam">
          <sweep_values>26000,22000</sweep_values>
          
        </capacity>
        
      </produces>
      <economics>
        <lifetime>27</lifetime>
      </economics>
    </Component>

    <Component name="turbine">
      <produces resource="electricity" dispatch="dependent">
        <consumes>steam</consumes>
        <capacity resource="steam">
          <fixed_value>-1e10</fixed_value>
        </capacity>
        <transfer>
          <linear>
            <rate resource="steam">-1</rate>
            <rate resource="electricity">0.5</rate>
          </linear>
        </transfer>
        
      </produces>
      <economics>
        <lifetime>27</lifetime>
        
      </economics>
    </Component>

    <Component name="electr_market">
      <demands resource="electricity" dispatch="dependent">
        <capacity>
          
          <fixed_value>0</fixed_value>
        </capacity>
      </demands>
      <economics>
        <lifetime>30</lifetime>
        <CashFlow name="e_sales" type="repeating" taxable='True' inflation='none' mult_target='False'>
          <driver>
            <Function method="electric_consume">transfers</Function>
            
          </driver>
          <reference_price>
            <fixed_value>0.5</fixed_value>
          </reference_price>
        </CashFlow>
      </economics>
    </Component>

   

    <Component name="electr_flex">
      <demands resource="electricity" dispatch="independent">
        <capacity>
          <ARMA>Load</ARMA>
          
        </capacity>
      </demands>
      <economics>
        <lifetime>30</lifetime>
        <CashFlow name="e_sales" type="repeating" taxable='True' inflation='none' mult_target='False'>
          <driver>
            <Function method="electric_consume">transfers</Function>
          </driver>
          <reference_price>
            <Function method="flex_price">transfers</Function>
          </reference_price>
        </CashFlow>
      </economics>
    </Component>

  </Components>

  <DataGenerators>
    <ARMA name='Signal' variable="Signal">arma1.pk</ARMA>
    <ARMA name='Load' variable="Time">arma.pk</ARMA>
    <Function name="transfers">transfers.py</Function>
  </DataGenerators>

</HERON>
"""

**Comment by andrewtrainor** [comment]
I had to make that a txt because it wouldn't let me upload an xml, let me know if you need any other information.

**Comment by PaulTalbot-INL** [comment]
Interesting. At minimum we should be giving you a better error, even if it's an input thing. I will try to look at this and see what might be happening.

**Comment by andrewtrainor** [comment]
great thanks!

**Comment by PaulTalbot-INL** [comment]
@andrewtrainor I notice you're using "Time" as the ARMA variable for "Load"; is that intentional? I assume "Time" is the monotonically increasing variable on which other variables depend ...

**Comment by andrewtrainor** [comment]
I tried using "Signal" as well. The arma was trained with the headers ,Time,Signal in the csv file. I got the same error with both variable names but I guess that It should be signal

**Comment by PaulTalbot-INL** [comment]
Okay. I agree that's probably not related to your signal.

I see that your `<ARMA>` node for `electr_flex` `capacity` doesn't have a `variable` parameter; that is, I see
```xml
<capacity>
  <ARMA>Load</ARMA>
</capacity>
```
but I expected to see
```xml
<capacity>
  <ARMA variable="Signal">Load</ARMA>
</capacity>
```
I see I failed to mark the `variable` parameter as "required"; I'll get that into a fix here. Can you try adding that, changing your variable from "Time" to "Signal", and see if that goes through?

**Comment by andrewtrainor** [comment]
Heron wrote all the files that time, thanks!
When running the raven on outer.xml it gave the error:
```
Traceback (most recent call last):
  File "/home/prism/repos/raven/framework/Driver.py", line 305, in <module>
    raven()
  File "/home/prism/repos/raven/framework/Driver.py", line 258, in raven
    simulation.run()
  File "/home/prism/repos/raven/framework/Simulation.py", line 784, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/prism/repos/raven/framework/Steps.py", line 338, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/prism/repos/raven/framework/Steps.py", line 663, in _localTakeAstepRun
    myLambda([finishedJob,outputs[outIndex]])
  File "/home/prism/repos/raven/framework/Steps.py", line 611, in <lambda>
    self._outputCollectionLambda.append( (lambda x: inDictionary['Model'].collectOutput(x[0],x[1]), outIndex) )
  File "/home/prism/repos/raven/framework/Models/Code.py", line 739, in collectOutput
    output.addRealization(rlz)
  File "/home/prism/repos/raven/framework/DataObjects/DataSet.py", line 227, in addRealization
    self.raiseAnError(KeyError,'Provided realization does not have all requisite values for object "{}": "{}"'.format(self.name,e.args[0]))
  File "/home/prism/repos/raven/framework/MessageHandler.py", line 98, in raiseAnError
    self.messageHandler.error(self,etype,msg,str(tag),verbosity,color)
  File "/home/prism/repos/raven/framework/MessageHandler.py", line 312, in error
    raise etype(message)
KeyError: 'Provided realization does not have all requisite values for object "grid": "electr_flex_capacity"'
```
Is there more that has to be added when using an ARMA as the capacity for the grid to meet than just the ARMA node?

**Comment by PaulTalbot-INL** [comment]
First, let me offer a markdown hint: multiline code can be added by surrounding with three backticks, turning
`example
of multline
using one backtick`
to 
```
example
of multiline
using three backticks
```

Note I edited your post just for the readability of that paste.

**Comment by andrewtrainor** [comment]
Here is with 3 it looks the same on my screen but hopefully it is better on your end,
```Traceback (most recent call last):
  File "/home/prism/repos/raven/framework/Driver.py", line 305, in <module>
    raven()
  File "/home/prism/repos/raven/framework/Driver.py", line 258, in raven
    simulation.run()
  File "/home/prism/repos/raven/framework/Simulation.py", line 784, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/prism/repos/raven/framework/Steps.py", line 338, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/prism/repos/raven/framework/Steps.py", line 663, in _localTakeAstepRun
    myLambda([finishedJob,outputs[outIndex]])
  File "/home/prism/repos/raven/framework/Steps.py", line 611, in <lambda>
    self._outputCollectionLambda.append( (lambda x: inDictionary['Model'].collectOutput(x[0],x[1]), outIndex) )
  File "/home/prism/repos/raven/framework/Models/Code.py", line 739, in collectOutput
    output.addRealization(rlz)
  File "/home/prism/repos/raven/framework/DataObjects/DataSet.py", line 227, in addRealization
    self.raiseAnError(KeyError,'Provided realization does not have all requisite values for object "{}": "{}"'.format(self.name,e.args[0]))
  File "/home/prism/repos/raven/framework/MessageHandler.py", line 98, in raiseAnError
    self.messageHandler.error(self,etype,msg,str(tag),verbosity,color)
  File "/home/prism/repos/raven/framework/MessageHandler.py", line 312, in error
    raise etype(message)
KeyError: 'Provided realization does not have all requisite values for object "grid": "electr_flex_capacity"'
```

**Comment by PaulTalbot-INL** [comment]
Second, I'm not 100% sure why that isn't working as expected. I'll have to look at it for a second.

**Comment by PaulTalbot-INL** [comment]
Update: as per usual, going chasing after one bug often leads to a nest of them. I'm squashing away, but haven't resolved enough for a PR yet.

**Comment by andrewtrainor** [comment]
Thanks again for looking into that

**Comment by PaulTalbot-INL** [comment]
I spent some time on understanding this, and will come back to it, but I have some pressing needs that are going to occupy my time the next couple days. Using an ARMA for capacity is going to be a struggle until I finish the fixes.

Do you truly want the grid _capacity_ to be stochastic, or do you want the price to be stochastic? You can treat the price through a Function that uses the ARMA, if that's a workaround you can use. At least until I can get back to this.

**Comment by dhill2522** [comment]
I think that should be sufficient for our needs at least for the next little while. So far we have been planning on modeling the grid load as being uncertain, but modeling the price uncertainty instead should be fine until we get a little further along.

Thanks for your work on this.

**Comment by andrewtrainor** [comment]
We aren’t concerned about the price at the moment, it was just for the grid instability. That sounds great though! when ever you have time
Thanks!
