### ISSUE TITLE
Using HERON OptimizedDispatch in HYBRID

### ISSUE THREAD

**Issue by BotrosHanna-INL** [idaholab/HERON#201]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
The optimized dispatch (the components variables that are optimized using HERON) need to be investigated using HYBRID to verify whether the the HERON optimized dispatch is feasible  or if any physical constraints are violated.

**Describe the solution you'd like**
The CSV file produced from HERON  and the HERON input XML file need to be used to create a new text file for the HYBRID users. Besides, HERON create several scenarios (samples). One sample only needs to be selected.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Should have been closed by #202. Closing now.
