### ISSUE TITLE
[DEFECT] Mac Documentation Failed

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/HERON#217]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
The user manual to be built

##### What did you see instead?
Import errors stopping the build process
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/74023858/195851747-b024752a-fdb7-43f4-ac34-7ded3aeb8e9c.png">

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. Update and build raven heron and teal
2. Activate raven_libraries environment
3. Try to build HERON documentation
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
I can't reproduce this issue as described. That error, however, is usually indicative of a failed or corrupt raven build. You can try rebuilding RAVEN to see if the issue is resolved. I am able to build HERON documentation successfully on macOS.

**Comment by mgarrouste** [comment]
Thanks for the advice, I must have skipped a step in the updating and building process.
