### ISSUE TITLE
[DEFECT] Optimization steps not printed

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/HERON#218]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
The opt_soln_0.csv should contain all the steps of the optimization

##### What did you see instead?
The opt_soln.png shows that the optimization has converged but the opt_soln_0.csv only shows a subset of the steps performed. 

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. run HERON case with input file provided
2. 
3. 
4. 
5. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?
[Archive.zip](https://github.com/idaholab/HERON/files/9803518/Archive.zip)

**Comment by dylanjm** [comment]
@mgarrouste can you update your attached archive to include everything required to run the case please? Things like the arma.pk and any custom functions required. This will allow me to run your case fully. Thanks.

**Comment by mgarrouste** [comment]
[Output_2018_2021_Braidwood_periodic.zip](https://github.com/idaholab/HERON/files/9810596/Output_2018_2021_Braidwood_periodic.zip)
[functions.py.zip](https://github.com/idaholab/HERON/files/9810601/functions.py.zip)

**Comment by mgarrouste** [comment]
This is still an issue and I will need to run HERON models very soon

**Comment by mgarrouste** [comment]
[HERON_issue.zip](https://github.com/idaholab/HERON/files/10059863/HERON_issue.zip)
Here are the necessary files to run my case and the opt_soln_0.csv and opt_path.png when I run it on the HPC. The png file shows at least 3 steps while only the first one is printed to the csv file

**Comment by mgarrouste** [comment]
Re-ran the case with persistence=7 instead of =3 and got these results: one more step is printed to the csv file so it seems like the issue is that the final result is not printed to the csv file
[opt_soln_0-2.csv](https://github.com/idaholab/HERON/files/10106398/opt_soln_0-2.csv)
![opt_path-2](https://user-images.githubusercontent.com/74023858/204349423-8990e8e4-3ca3-46d6-accf-9da6488b0408.png)

**Comment by dylanjm** [comment]
This issue should be solved by #241
