### ISSUE TITLE
[TASK] Workbench Integration

### ISSUE THREAD

**Issue by lefebvrera** [idaholab/HERON#259]
--------
NEAMS Workbench Integration
--------

**Is your feature request related to a problem? Please describe.**

The NEAMS Workbench provides user input accelerators such as input auto-completion, quick navigation, documentation, job launch, and output visualization. DOE IES campaign has identified FORCE-Workbench integration as a viable path forward for improving the user experience. 

Work is performed in completion of DOE IES milestone 'M3CT-23OR1202162-Integration Report FORCE with NEAMS Workbench'

**Describe the solution you'd like**
This work enables HERON to communicate input requirements to the NEAMS Workbench. The Hierarchical Input Validation Engine ([HIVE](https://code.ornl.gov/neams-workbench/wasp/-/blob/master/wasphive/README.md)) input schema format has been employed and a command line option of `--definition` allows the HERON input schema to be communicated to the user/Workbench.  This enhancement, in combination with the conversion of the XML to extra-definition driven input (EDDI) input format, provides immediate integration of HERON into the NEAMS Workbench. EDDI format, coupled with the input definition provided by this HERON update, preserves the input structure and data but removes the cumbersome XML syntax.

E.g., the simple workshop problem native XML vs EDDI format can be observed below.

![Screen Shot 2023-02-14 at 11 23 14 AM](https://user-images.githubusercontent.com/19177911/218799757-3df633c0-5f79-4458-acad-b3c99a2d836d.jpg)

Items to note include ~45% input character reduction and Workbench integration

 <img width="1069" alt="Screen Shot 2023-02-14 at 1 34 33 PM" src="https://user-images.githubusercontent.com/19177911/218826986-c31d2974-eae7-478a-b927-929f32582f10.png">

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by lefebvrera** [comment]
@PaulTalbot-INL @dylanjm per my understanding of the HERON QA process here is an issue to support Workbench integration

**Comment by PaulTalbot-INL** [comment]
approved to close via #268.
