### ISSUE TITLE
[DEFECT] Error when running opt mode, templates need an update

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/HERON#318]
--------
Defect Description
--------

**Describe the defect**
Running optimization mode causes an error due to a recent RAVEN update (https://github.com/idaholab/raven/pull/2177)

##### What did you expect to see happen?
Running the `optimization_settings` integration test should have passed running HERON tests via Rook. 

##### What did you see instead?

```
Traceback (most recent call last):
  File "C:\Users\sotogj\projects\raven\raven_framework.py", line 25, in <module>
    sys.exit(main(True))
  File "C:\Users\sotogj\projects\raven\ravenframework\Driver.py", line 151, in main
    simulation.XMLread(root,runInfoSkip=set(["DefaultInputFile"]),xmlFilename=inputFile)
  File "C:\Users\sotogj\projects\raven\ravenframework\Simulation.py", line 381, in XMLread
    self.instantiateEntities(xmlNode, runInfoSkip, xmlFilename)
  File "C:\Users\sotogj\projects\raven\ravenframework\Simulation.py", line 494, in instantiateEntities
    entity.readXML(block, varGroups, globalAttributes=globalAttributes)
  File "C:\Users\sotogj\projects\raven\ravenframework\BaseClasses\BaseEntity.py", line 99, in readXML
    self._readMoreXML(xmlNode)
  File "C:\Users\sotogj\projects\raven\ravenframework\Steps\Step.py", line 148, in _readMoreXML
    self._handleInput(paramInput)
  File "C:\Users\sotogj\projects\raven\ravenframework\Steps\Step.py", line 195, in _handleInput
    self._localInputAndCheckParam(paramInput)
  File "C:\Users\sotogj\projects\raven\ravenframework\Steps\MultiRun.py", line 59, in _localInputAndCheckParam
    SingleRun._localInputAndCheckParam(self,paramInput)
  File "C:\Users\sotogj\projects\raven\ravenframework\Steps\SingleRun.py", line 99, in _localInputAndCheckParam
    Models.validate(self.parList[modelIndex][2], role, toBeTested[role])
  File "C:\Users\sotogj\projects\raven\ravenframework\Models\Factory.py", line 50, in validate
    return factory.returnClass(className).localValidateMethod(role, what)
  File "C:\Users\sotogj\projects\raven\ravenframework\Models\Model.py", line 190, in localValidateMethod
    raise IOError('The number of times class = '+str(tester['class'])+' type= ' +str(tester['type'])+' is used as '+str(who)+' is improper. Number of allowable times is '+str(tester['multiplicity'])+'.Got '+str(tester['tempCounter']))
OSError: The number of times class = Optimizers type= ['GradientDescent', 'GeneticAlgorithm', 'SimulatedAnnealing', 'BayesianOptimizer'] is used as Optimizer is improper. Number of allowable times is 1.Got 0
```

##### Do you have a suggested fix for the development team?
Switch the Optimizer class type from 'FiniteDifference' to 'GradientDescent' in the outer XML template.

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
This issue was addressed as part of #315
