### ISSUE TITLE
[TASK] Economic Uncertainty Quantification in HERON

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/HERON#330]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
In HERON, inputs for component cashflows (`driver`, `reference_price`, `reference_driver`, `scaling_factor_x`) can take the shape of a variety of ValuedParams ( e.g., static history or synthetic history, Function, FixedValue). Some cost values, however, have uncertainty associated with their final values and it would be great to capture this uncertainty within HERON analysis. 

**Describe the solution you'd like**
A new ValuedParam could be introduced to consider uncertainty within an input. This uncertainty could be quantified by some sort of distribution; the desired input can take the value of a random variable sampled from said distribution. HERON can take advantage of the Monte Carlo sampling technique (already used in the inner loops of the RAVEN-runs-RAVEN workflow) to sample from these cost distributions at the same time as synthetic histories are generated from given TSA ROMs. 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved to close via #331 .
