### ISSUE TITLE
[DEFECT] Running HERON opt using BayesianOpt still creates an outer XML with GradientDescent

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/HERON#350]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
Running HERON optimization using the Bayesian Optimizer.

##### What did you see instead?
When running HERON in `opt` mode using the BayesianOpt algorithm, the `outer.xml` file is written still with the GradientDescent algorithm.

##### Do you have a suggested fix for the development team?
Quick fix in the `template_driver.py` since it is looking for "BayesianOptimizer" rather than "BayesianOpt." The regression test should also be updated. 

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
![image](https://github.com/idaholab/HERON/assets/109242402/925ad23a-b32b-4978-b112-505f77390baf)

![image](https://github.com/idaholab/HERON/assets/109242402/94db2ed3-b372-47d0-b00f-d955b0ebf475)

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Due to the newness of the Bayesian implementation, we may not need to send out a notification. If you want to post a note about it, however, that is fine as well.

Approved to close via #356.
