### ISSUE TITLE
[TASK] Check more locations for test data files

### ISSUE THREAD

**Issue by j-bryan** [idaholab/HERON#359]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
The FORCE standalone installation contains some HERON examples and the accompanying SyntheticHistory/ARMA ROM files. However, the %HERON_DATA% default location is not easily accessible to users for this installation type. Adding another location to check for these files would facilitate a better user experience for those using the standalone installation and wishing to run the included examples.

**Describe the solution you'd like**
Add an additional location to check for the `data` directory currently located in HERON's root directory.

**Describe alternatives you've considered**
Edit the example HERON case files to point directly to the included ROMs. However, this presents more difficulties when copying selected tests to the FORCE build package.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #360
