### ISSUE TITLE
[TASK] Allow users to specify "case-info" constants

### ISSUE THREAD

**Issue by dylanjm** [idaholab/HERON#38]
--------
Issue Description
--------
Users should be able to provide information pertaining to a case that would be valuable to have at the end of the RAVEN stack. This could be information that would help distinguish between runs when the data contains a multilevel structure. 

For example, If a user is examining effect on marginal costs across a set of varying market demand scenarios for a set of different markets, a user should be able to specify something like:

```xml
<Case name="Sweep_Runs">
...
  <caseinfo>
    <state>California</state>
    <scenario>CarbonTax</scenario>
  </caseinfo>
...
</Case>
```

This would allow HERON's template builder to handle a broader range of cases.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
More generally, this would allow passing of constants through that aren't strictly the capacities of units; for example, buy-sell thresholds for batteries in a theoretical marginal dispatch.

This should be straightforward by adapting the workflow writer so that these are `constant`s in the Outer sampler, passed through to the RAVEN model in the Outer, and made accessible to the DispatchManager model in the Inner.

**Comment by PaulTalbot-INL** [comment]
Approved to close via #41
