### ISSUE TITLE
[DEFECT] Tighter pyomo optimization tolerance option

### ISSUE THREAD

**Issue by wanghy-anl** [idaholab/HERON#67]
--------
Defect Description
--------

I developed a validator for a 3-unit system composed of Balance of Plant (BOP), Secondary Energy Source (SES) and Thermal Energy Storage (TES). Under some situations the dispatcher cannot observe the validation constraints identified in a previous solve attempt. I outputted the dispatched value (curr) from pyomo and the constraints (V1) calculated by the validator when validation concerns are raised, see the docx file attached.
[Dispatcher Issue.docx](https://github.com/idaholab/HERON/files/5914601/Dispatcher.Issue.docx)

##### What did you expect to see happen?
I am expecting that on Attempt 4, unit = TES, t=12, the dispatcher can issue a "curr" value lower than the upper constraint (V1=  501003.691) found in Attempt 3.

##### What did you see instead?
On Attempt 4, 5, ..., 101, unit = TES, t=12, the dispatcher never observe the upper constraint (V1=  501003.691) found in the previous solve attempt. In fact, only the upper constraint (V1=  501004.074) found in Attempt 2 is observed. The gap between “curr” and “V1” in Attempts 4 and beyond remain the same 0.383.

##### Do you have a suggested fix for the development team?
I contacted Paul Talbot and we think this issue is not associated with the numerical precision or tolerance. In the attached word file there is also a cyan highlighted case:
At Attempt 3, t=12, the SES has a dispatched value “curr= 18.557” and a lower constraint “V1=  19.317”, and the gap between them is 0.76. Later in Attempt 4, t=12, this constraint is observed. 

It is interesting that a gap of 0.76 can be observed but a gap of 0.383 cannot be observed, maybe there is a threshold of such gap in pyomo dispatcher?

**Describe how to Reproduce**
1. Contact me directly and I can add you to my repository access list. I am providing the input file here, but it requires the customized validator and the ARMA to run.
[heron_input_para_BOP_SES_TES_MW.txt](https://github.com/idaholab/HERON/files/5914608/heron_input_para_BOP_SES_TES_MW.txt)
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Version: 10.0.18363 Build 18363
 - Dependencies Installation: CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@alfoa

**Comment by PaulTalbot-INL** [comment]
On further investigation, this is a tolerance issue. The validator in use was imposing a 1e-6 absolute tolerance on a 5e5 value, which was beyond the numerical tolerance of the optimizing solve.

A suggested improvement might be to see if there's a value we can access to tweak the solver's tolerance level, and expose it to the user; or, perhaps, the tolerance for the solver could be propagated to the validator.

**Comment by PaulTalbot-INL** [comment]
Enough requests came in for this that we've gone ahead with an implementation. We have to do a specific implementation per solver (e.g. glpk, cbc, ipopt, gurobi, cplex, ...) so we've done the three commonly-used open source solvers first. We can add others on request.
