### ISSUE TITLE
[TASK] Read optimization window size from input file

### ISSUE THREAD

**Issue by wanghy-anl** [idaholab/HERON#77]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
I would like to request a feature that the optimization window length can be specified in the input file. Currently the window length is fixed to 24 hours, as listed in Line 70 of the "pyomo_dispatch.py".

**Describe the solution you'd like**
Allow the pyomo to read the <time_discretization> section for the <num_steps> entry from the input file, and update the "self._window_len" in the "pyomo_dispatch.py" accordingly. Paul said it would be possible to expose this window size to the user, by registering it in the “get_input_specs” and reading it in the “read_input”.

**Describe alternatives you've considered**
N/A

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
FYI a fix for this has been posted as a pull request, so the next submodule update for RAVEN should include this feature.

**Comment by wanghy-anl** [comment]
Thank you Paul!
