### ISSUE TITLE
Installation via plugin on RAVEN does not work. 

### ISSUE THREAD

**Issue by klfrick2** [idaholab/HERON#8]
--------
Issue Description
--------
##### What did you expect to see happen?
A full clean plugin install. 

##### What did you see instead?
Same issue has happened for other users. 

![HERON Issue](https://user-images.githubusercontent.com/42416409/89924884-de1e8500-dbbf-11ea-9537-4cb3f56e36b2.png)

##### Do you have a suggested fix for the development team?
Some rights requirements need to be turned off? 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Interesting. The submodule updater should be using https instead of ssh; we don't want to give specific access to everyone that wants to use the code.

I will have to try and duplicate this with a non-subscribed git user and see if I can get the same message. Do you have a HERON folder under `raven/plugins`? If so, and if you remove it before installing the plugin, does it give the same message?

**Comment by PaulTalbot-INL** [comment]
I discovered that the submodule registration inherited using my settings (ssh) instead of the publicly-friendly one (https). That PR should fix it; @klfrick2 can you try manually making this change and seeing if it goes through for you?

**Comment by PaulTalbot-INL** [comment]
This has been closed by the idaholab/raven#1308 in RAVEN.
