### ISSUE TITLE
[TASK] Allow project time of 1 year

### ISSUE THREAD

**Issue by wanghy-anl** [idaholab/HERON#80]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
HERON can accept the project time equal to one year

##### What did you see instead?
A crash of RAVEN inner, 
```
( 1.33 sec) STEP MULTIRUN : Message -> *** Initialization done ***
( 1.33 sec) STEP MULTIRUN : Message -> *** Beginning run ***
( 1.35 sec) EnsembleModel : DEBUG -> Submitting model flex
( 74.31 sec) ARMA : DEBUG -> Evaluating cycle 0
( 1.35 sec) DataSet : Warning -> Variables provided: dict_keys(['SampledVars', 'SampledVarsPb', 'crowDist', 'prefix', 'PointProbability', 'ProbabilityWeight', 'SamplerType', 'ProbabilityWeight-scaling', 'ProbabilityWeight-BOP_capacity', 'ProbabilityWeight-SES_capacity', 'ProbabilityWeight-TES_capacity', 'ProbabilityWeight-electr_market_capacity', 'ProbabilityWeight-denoises', 'jobHandler', 'uniqueHandler', 'scaling', 'Cycle', 'netLoad', 'Time'])
( 1.35 sec) DataSet : ERROR -> Provided realization does not have all requisite values for object "flex_samples": "Year"
--------------------------------------------------
There were 1 warnings during the simulation run:
(1 time) Variables provided: dict_keys(['SampledVars', 'SampledVarsPb', 'crowDist', 'prefix', 'PointProbability', 'ProbabilityWeight', 'SamplerType', 'ProbabilityWeight-scaling', 'ProbabilityWeight-BOP_capacity', 'ProbabilityWeight-SES_capacity', 'ProbabilityWeight-TES_capacity', 'ProbabilityWeight-electr_market_capacity', 'ProbabilityWeight-denoises', 'jobHandler', 'uniqueHandler', 'scaling', 'Cycle', 'netLoad', 'Time'])
--------------------------------------------------
( 1.36 sec) Job Handler : Message -> Process Failed <Runners.SharedMemoryRunner.SharedMemoryRunner object at 0x0000018319E92108> internal returnCode -1
( 1.36 sec) STEP MULTIRUN : DEBUG -> the job "1" has failed.
```
##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
This would be a new feature, where only a single year project time is considered. I don't know of a use case for this, except for debugging purposes, which would be useful.

**Comment by PaulTalbot-INL** [comment]
There is no new activity planned on this, and is handled by the debugging mode. Archiving for future reference.
