### ISSUE TITLE
[TASK] optimizing <multiplier> in opt mode

### ISSUE THREAD

**Issue by sobincho** [idaholab/HERON#92]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
I am conducting capacity optimization (outer level) on a Solar-Electric storage-only configuration. Additionally, I want the solar dispatch to follow a trained FARMA signal, but the dispatch amplitude (solar capacity) can be changed by the <multiplier> node. So, my inital HERON input would look like: 
![image](https://user-images.githubusercontent.com/81767444/121462276-60154100-c97e-11eb-8388-4403de14c033.png)

========
 However, I run into error message :"OSError: Component.produces.capacity.multiplier: float() argument must be a string or a number, not 'NoneType'" and I assume this is due to the node  <multiplier><opt_bounds>0, 1</opt_bounds></multiplier>

**Describe the solution you'd like**
I hope "multiplier" node takes "sweep_values" ,"variable" node as well 

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
This is covered by #121.
